//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReSharperPlugin.DevOpsTCPlugin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ReSharperPlugin.DevOpsTCPlugin.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All data for the token must be completed
        ///.
        /// </summary>
        internal static string AllDataForTokenIsRequired {
            get {
                return ResourceManager.GetString("AllDataForTokenIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already assigned test cases.
        /// </summary>
        internal static string AlreadyAssignedTC {
            get {
                return ResourceManager.GetString("AlreadyAssignedTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignment.
        /// </summary>
        internal static string AssignmentDialogTitle {
            get {
                return ResourceManager.GetString("AssignmentDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assing.
        /// </summary>
        internal static string AssingButton {
            get {
                return ResourceManager.GetString("AssingButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check token data.
        /// </summary>
        internal static string CheckTokenData {
            get {
                return ResourceManager.GetString("CheckTokenData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to assign the indicated test to the Test Case:.
        /// </summary>
        internal static string ConfirmAssignmentForTestCase {
            get {
                return ResourceManager.GetString("ConfirmAssignmentForTestCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the token:
        ///.
        /// </summary>
        internal static string DeleteTokenConfirmationMessage {
            get {
                return ResourceManager.GetString("DeleteTokenConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The action allows you to assign test information to the Associated Automation tab in Azure Test Case
        ///.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect test indicated
        ///.
        /// </summary>
        internal static string IncorrectTest {
            get {
                return ResourceManager.GetString("IncorrectTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link copied to clipboard.
        /// </summary>
        internal static string LinkCopied {
            get {
                return ResourceManager.GetString("LinkCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage tokens.
        /// </summary>
        internal static string ManageTokensTitle {
            get {
                return ResourceManager.GetString("ManageTokensTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No token. Add the AZURE_DEVOPS_PAT environment variable with the token.
        ///.
        /// </summary>
        internal static string NoPATMessage {
            get {
                return ResourceManager.GetString("NoPATMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No token selected..
        /// </summary>
        internal static string NoTokenSelected {
            get {
                return ResourceManager.GetString("NoTokenSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        internal static string Organization {
            get {
                return ResourceManager.GetString("Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization cannot be empty. Enter it manually or add it as an AZURE_DEVOPS_ORGANIZATION environment variable.
        ///.
        /// </summary>
        internal static string OrganizationCannotBeEmpty {
            get {
                return ResourceManager.GetString("OrganizationCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The organization project cannot be empty. Enter it manually or add it as an AZURE_DEVOPS_ORGANIZATION_PROJECT environment variable.
        ///.
        /// </summary>
        internal static string OrganizationProjectCannotBeEmpty {
            get {
                return ResourceManager.GetString("OrganizationProjectCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization settings.
        /// </summary>
        internal static string OrganizationSettingsLabel {
            get {
                return ResourceManager.GetString("OrganizationSettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automated test name.
        /// </summary>
        internal static string PathToTest {
            get {
                return ResourceManager.GetString("PathToTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAT.
        /// </summary>
        internal static string PatLabel {
            get {
                return ResourceManager.GetString("PatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automated test storage.
        /// </summary>
        internal static string ProjectDll {
            get {
                return ResourceManager.GetString("ProjectDll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DLL name of the project containing the test cannot be empty..
        /// </summary>
        internal static string ProjectDllCannotBeEmpty {
            get {
                return ResourceManager.GetString("ProjectDllCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project in the organization.
        /// </summary>
        internal static string ProjectInOrganization {
            get {
                return ResourceManager.GetString("ProjectInOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save settings for project.
        /// </summary>
        internal static string SaveSettingsForProject {
            get {
                return ResourceManager.GetString("SaveSettingsForProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings saved for project
        ///.
        /// </summary>
        internal static string SettingsSaved {
            get {
                return ResourceManager.GetString("SettingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the specific test to be assigned
        ///.
        /// </summary>
        internal static string ShouldSelectCurrentTest {
            get {
                return ResourceManager.GetString("ShouldSelectCurrentTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution.
        /// </summary>
        internal static string Solution {
            get {
                return ResourceManager.GetString("Solution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you like my work? Buy me a coffee :)
        ///.
        /// </summary>
        internal static string SupportMyWork {
            get {
                return ResourceManager.GetString("SupportMyWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Case already has the specified test assigned. I&apos;m skipping it.
        ///.
        /// </summary>
        internal static string TestAlreadyAssigned {
            get {
                return ResourceManager.GetString("TestAlreadyAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Case Azure ID.
        /// </summary>
        internal static string TestCaseAzureId {
            get {
                return ResourceManager.GetString("TestCaseAzureId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must provide a Test Case ID to assign a test to a TestCase..
        /// </summary>
        internal static string TestCaseIdCannotBeEmpty {
            get {
                return ResourceManager.GetString("TestCaseIdCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string TestCaseIdLabel {
            get {
                return ResourceManager.GetString("TestCaseIdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string TestCaseTitleLabel {
            get {
                return ResourceManager.GetString("TestCaseTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Case has been updated.
        /// </summary>
        internal static string TestCaseUpdated {
            get {
                return ResourceManager.GetString("TestCaseUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The test path cannot be empty.
        ///.
        /// </summary>
        internal static string TestPathCannotBeEmpty {
            get {
                return ResourceManager.GetString("TestPathCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automated test type.
        /// </summary>
        internal static string TestType {
            get {
                return ResourceManager.GetString("TestType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign a test to Azure Test Case
        ///.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token:.
        /// </summary>
        internal static string Token {
            get {
                return ResourceManager.GetString("Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token is required.
        /// </summary>
        internal static string TokenIsRequired {
            get {
                return ResourceManager.GetString("TokenIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Test Case with the specified ID was found.
        ///.
        /// </summary>
        internal static string WorkitemNotFound {
            get {
                return ResourceManager.GetString("WorkitemNotFound", resourceCulture);
            }
        }
    }
}
